name: build html

on:
  push:
    branches:
      - sources

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git credentials
      run: |
        git config --global user.name "losehu"
        git config --global user.email "wu58430@126.com"
        
    - name: Install Node.js and npm
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Hexo
      run: npm install -g hexo-cli
      
    - name: Install Hexo deployer
      run: npm install hexo-deployer-git --save
           
    - name: Deploy to GitHub Pages
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}  # 使用 GitHub Secrets 中的 GH_TOKEN
      run: |
        hexo clean
        hexo generate
        hexo deploy --token $GH_TOKEN  # 使用环境变量传递令牌
